# Where things are
destination:  ./site/old
data_dir:     ./_data
collections:  null

# Exclude DIR
exclude: [/less]

# Outputting
permalink:     pretty
paginate_path: /page:num
timezone:      Australia/Melbourne

# Site Meta
url: http://unihack.net/old
description: "UNIHACK is Melbourne's premier student hackathon, organised by WIRED Monash"
